Fixed blank spaces for null atts, made search bar longer
CS340-21/BookRecommendations pull request #45
Opened 2021-04-24 17:34 UTC by braymar

2021-04-24 18:28 UTC, awillif requested changes
Could you indent the that divs correctly? ie 
<div>
    content
</div>

2021-04-24 21:57 UTC, braymar commented
> Could you indent the divs correctly? ie

I fixed the indentation of the divs

2021-04-25 03:07 UTC, Gr-Anderson approved these changes

2021-04-25 17:20 UTC, awillif approved these changes

2021-04-25 17:20 UTC, merged